spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DATABASE_HOST:localhost}:${POSTGRES_DATABASE_PORT:5432}/${POSTGRES_DATABASE_NAME:linkedin_profile_searcher}
    username: ${POSTGRES_DATABASE_USERNAME:postgres}
    password: ${POSTGRES_DATABASE_PASSWORD:password}
  flyway:
    user: postgres
    password: password
    baseline-version: 1.0
    baseline-on-migrate: true
    baseline-description: baseline-description
    locations: classpath:db/migration

  profiles:
    active: local

com:
  phantom:
    buster:
      phantom-id: 814818359720730
      phantom-buster-api-key: GXDWqkWxhbHATLTWjNbnyaNwhmEfEjaidJmCQHD8zDk
      linked-in-session-cookie: AQEDATB5kfwE0dg0AAABmAOn488AAAGYJ7Rnz1YAqQAFtlc5_BcpfNLzTNQbLm15lqyAZZ0uTSMlNXBFT4KwFuMBYvzID8BMlnt3M-e7YVowf9KZax0sv019N_W0Du6MdxNojVCvkad-2xnwMiGs9fQj